services:
#  api:
#    build: .
#    container_name: "rest-api"
#    environment:
#      DB_USERNAME: "${POSTGRES_USER}"
#      DB_PASSWORD: "${POSTGRES_PASSWORD}"
#      DB_DB: "${POSTGRES_DB}"
#      DB_HOST: "pg-prod"
#      DB_PORT: "5432"
#      SSL_MODE: "disable"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - pg-prod
#    networks:
#      - fullstack

  pg-local:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:

networks:
  fullstack:
    driver: bridge
